name: 'Cognitive Ecosystem: Issue Generation Meta-Framework'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: 'Cognitive Bootstrap: Repository Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: 'Memory System: Setup Guix Environment'
        run: |
          # Install Guix for reproducible builds (non-interactive)
          wget https://git.savannah.gnu.org/cgit/guix.git/plain/etc/guix-install.sh
          chmod +x guix-install.sh
          yes "" | sudo ./guix-install.sh
          export PATH="/var/guix/profiles/per-user/root/current-guix/bin:$PATH"
          guix --version || echo "Guix installation in progress..."

      - name: Setup and Build
        uses: ./.github/actions/setup-and-build

      - name: Run type check
        run: pnpm run typecheck

      # - name: Run ESLint
      #   run: pnpm run lint

      - name: Run tests
        run: pnpm run test

